const pendingActivities = [
  {
    username: 'John Wick',
    project: 'White Knight',
    document: 'Intern N.D.A (Unpaid)',
    date: '12/08/2024',
    status: 'In Progress',
  },
  {
    username: 'Alice Johnson',
    project: 'Skyline',
    document: 'Project Proposal',
    date: '15/08/2024',
    status: 'In Progress',
  },
  {
    username: 'Bob Williams',
    project: 'Deep Blue',
    document: 'Contract Agreement',
    date: '20/08/2024',
    status: 'In Progress',
  },
  {
    username: 'Sarah Connor',
    project: 'Cybernet',
    document: 'Security Compliance Report',
    date: '10/08/2024',
    status: 'In Progress',
  },
  {
    username: 'Ethan Hunt',
    project: 'Ghost Protocol',
    document: 'Confidentiality Agreement',
    date: '18/08/2024',
    status: 'In Progress',
  },
  {
    username: 'Lara Croft',
    project: 'Tomb Raider',
    document: 'Exploration Permit',
    date: '22/08/2024',
    status: 'In Progress',
  },
  {
    username: 'Bruce Wayne',
    project: 'Dark Knight',
    document: 'Patent Filing',
    date: '25/08/2024',
    status: 'In Progress',
  },
  {
    username: 'Diana Prince',
    project: 'Amazon Code',
    document: 'Tech Compliance',
    date: '28/08/2024',
    status: 'In Progress',
  },
  {
    username: 'Tony Stark',
    project: 'Iron Shield',
    document: 'Prototype Testing Report',
    date: '30/08/2024',
    status: 'In Progress',
  },
  {
    username: 'Steve Rogers',
    project: 'Super Soldier',
    document: 'Military Research Agreement',
    date: '05/09/2024',
    status: 'In Progress',
  },
  {
    username: 'Clark Kent',
    project: 'Metropolis Guardian',
    document: 'News Editorial Agreement',
    date: '08/09/2024',
    status: 'In Progress',
  },
  {
    username: 'Peter Parker',
    project: 'Web Slinger',
    document: 'Photography Contract',
    date: '10/09/2024',
    status: 'In Progress',
  },
  {
    username: 'Natasha Romanoff',
    project: 'Black Widow Ops',
    document: 'Covert Operations NDA',
    date: '12/09/2024',
    status: 'In Progress',
  },
  {
    username: 'Barry Allen',
    project: 'Speed Force',
    document: 'Time Travel Study',
    date: '15/09/2024',
    status: 'In Progress',
  },
  {
    username: 'Hal Jordan',
    project: 'Green Lantern Corps',
    document: 'Intergalactic Treaty',
    date: '18/09/2024',
    status: 'In Progress',
  },
];

export default pendingActivities;
