const clientUserConst = [
  // Existing users
  {
    mail: 'username1@gmail.com',
    userId: '11',
    name: 'Mia Turner',
    type: 'Employee',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
      { name: 'Security Compliance' },
      { name: 'Confidentiality' },
    ],
  },
  {
    mail: 'username2@gmail.com',
    userId: '12',
    name: 'Lucas Scott',
    type: 'Client',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
    ],
  },
  {
    mail: 'username3@gmail.com',
    userId: '101',
    name: 'Jake Williams',
    type: 'Intern',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
      { name: 'Security Compliance' },
      { name: 'Confidentiality' },
    ],
  },
  {
    mail: 'username4@gmail.com',
    userId: '102',
    name: 'Emma Morgan',
    type: 'Employee',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
      { name: 'Security Compliance' },
      { name: 'Confidentiality' },
    ],
  },
  {
    mail: 'username4@gmail.com',
    userId: '103',
    name: 'Chloe Cooper',
    type: 'Employee',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
      { name: 'Security Compliance' },
      { name: 'Confidentiality' },
    ],
  },
  {
    mail: 'username5@gmail.com',
    userId: '104',
    name: 'Noah Carter',
    type: 'Client',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
      { name: 'Security Compliance' },
      { name: 'Confidentiality' },
    ],
  },
  {
    mail: 'username6@gmail.com',
    userId: '105',
    name: 'Ava Brooks',
    type: 'Client',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
      { name: 'Security Compliance' },
      { name: 'Confidentiality' },
    ],
  },
  {
    mail: 'username7@gmail.com',
    userId: '106',
    name: 'Ethan Foster',
    type: 'Intern',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
      { name: 'Security Compliance' },
      { name: 'Confidentiality' },
    ],
  },
  {
    mail: 'username8@gmail.com',
    userId: '107',
    name: 'Sophia Hayes',
    type: 'Employee',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
      { name: 'Security Compliance' },
      { name: 'Confidentiality' },
    ],
  },
  {
    mail: 'username9@gmail.com',
    userId: '108',
    name: 'Liam Bennett',
    type: 'Employee',
    category: 'Client',
    date: '24-02-2024',
    documents: [
      { name: 'Intern NDA' },
      { name: 'Project Proposal' },
      { name: 'Contract' },
      { name: 'Security Compliance' },
      { name: 'Confidentiality' },
    ],
  },
];

export default clientUserConst;
