const userHistory = [
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'upload',
    data: 'NDA_Contract_v1.pdf',
    date: '12/12/2025',
    time: '13:05:12',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'edit',
    data: 'Employee_Record.docx',
    date: '13/12/2025',
    time: '09:15:33',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'delete',
    data: 'Temp_File.txt',
    date: '13/12/2025',
    time: '09:17:10',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'upload',
    data: 'ProjectPlan_2026.xlsx',
    date: '13/12/2025',
    time: '09:20:00',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'view',
    data: 'OnboardingChecklist.pdf',
    date: '13/12/2025',
    time: '10:12:45',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'upload',
    data: 'Budget2025.xlsx',
    date: '14/12/2025',
    time: '08:05:33',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'comment',
    data: 'Budget2025.xlsx',
    date: '14/12/2025',
    time: '08:30:25',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'download',
    data: 'ComplianceGuide.pdf',
    date: '14/12/2025',
    time: '09:11:44',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'edit',
    data: 'HR_Policies.docx',
    date: '15/12/2025',
    time: '11:22:10',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'upload',
    data: 'Training_Material.pptx',
    date: '15/12/2025',
    time: '12:00:00',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'archive',
    data: 'OldClientList.csv',
    date: '15/12/2025',
    time: '14:45:20',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'view',
    data: 'ExpensePolicy.pdf',
    date: '16/12/2025',
    time: '10:10:10',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'upload',
    data: 'ClientInvoice_Nov.pdf',
    date: '16/12/2025',
    time: '11:30:45',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'edit',
    data: 'ClientInvoice_Nov.pdf',
    date: '16/12/2025',
    time: '11:45:22',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'upload',
    data: 'MeetingNotes_Dec.pdf',
    date: '17/12/2025',
    time: '09:50:12',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'delete',
    data: 'DraftProposal.docx',
    date: '17/12/2025',
    time: '10:20:00',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'edit',
    data: 'AnnualReport_Outline.docx',
    date: '17/12/2025',
    time: '11:30:33',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'view',
    data: 'ClientList_2025.csv',
    date: '18/12/2025',
    time: '08:00:00',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'comment',
    data: 'TeamCalendar.ics',
    date: '18/12/2025',
    time: '08:45:50',
  },
  {
    userId: '21',
    name: 'Sophia Reynolds',
    type: 'System',
    activity: 'upload',
    data: 'PerformanceReview_Template.docx',
    date: '18/12/2025',
    time: '09:15:00',
  },
];

export default userHistory;
