const ProjectConst = [
  {
    projectId: 1,
    project: 'White Knight',
    Team: 'Intern N.D.A ',
    date: '12/08/2024',
    status: 'Finished',
  },
  {
    projectId: 2,
    project: 'Skyline',
    Team: 'Project Proposal',
    date: '15/08/2024',
    status: 'Finished',
  },
  {
    projectId: 3,
    project: 'Deep Blue',
    Team: 'Contract ',
    date: '20/08/2024',
    status: 'Finished',
  },
  {
    projectId: 4,
    project: 'Cybernet',
    Team: 'Security Compliance ',
    date: '10/08/2024',
    status: 'Finished',
  },
  {
    projectId: 5,
    project: 'Ghost Protocol',
    Team: 'Confidentiality ',
    date: '18/08/2024',
    status: 'Finished',
  },
  {
    projectId: 6,
    project: 'Tomb Raider',
    Team: 'Exploration Permit',
    date: '22/08/2024',
    status: 'Finished',
  },
  {
    projectId: 7,
    project: 'Dark Knight',
    Team: 'Patent Filing',
    date: '25/08/2024',
    status: 'Finished',
  },
  {
    projectId: 8,
    project: 'Amazon Code',
    Team: 'Tech Compliance',
    date: '28/08/2024',
    status: 'Finished',
  },
  {
    projectId: 9,
    project: 'Iron Shield',
    Team: 'Prototype Testing ',
    date: '30/08/2024',
    status: 'Finished',
  },
  {
    projectId: 10,
    project: 'Super Soldier',
    Team: 'Military Research ',
    date: '05/09/2024',
    status: 'Finished',
  },
  {
    projectId: 11,
    project: 'Metropolis Guardian',
    Team: 'News Editorial ',
    date: '08/09/2024',
    status: 'Finished',
  },
  {
    projectId: 12,
    project: 'Web Slinger',
    Team: 'Photography ',
    date: '10/09/2024',
    status: 'Finished',
  },
  {
    projectId: 13,
    project: 'Black Widow Ops',
    Team: 'Covert Operations ',
    date: '12/09/2024',
    status: 'Finished',
  },
  {
    projectId: 14,
    project: 'Speed Force',
    Team: 'Time Travel ',
    date: '15/09/2024',
    status: 'Finished',
  },
  {
    projectId: 15,
    project: 'Green Lantern Corps',
    Team: 'Intergalactic ',
    date: '18/09/2024',
    status: 'Finished',
  },
];

export default ProjectConst;
